export const newsArticles = [
  {
    "title": "Should We Tell Our Tween Daughter That Her Father Had a Nose Job?",
    "url": "https://www.nytimes.com/2024/08/21/style/nose-job-discussion-child.html",
    "image": null,
    "description": "When a couple’s 12-year-old starts to point out that no one else in the family seems to have a nose like hers, they can’t agree whether to tell her why.",
    "author": "Alice Johnson",
    "imgAuthor": "natan.jpg",
    "date_create": "2024-08-21T09:30:00+00:00",
    "theme": "Família e Identidade",
  },
  {
    "title": "Explaining Claims About Tim Walz’s Military Service",
    "url": "https://www.nytimes.com/2024/08/21/us/politics/tim-walz-military-service.html",
    "image": "https://static01.nyt.com/images/2024/08/20/multimedia/00dc-factcheck-walz-hmfz/00dc-factcheck-walz-hmfz-articleLarge.jpg",
    "description": "Four veterans who investigate claims of fraudulent military service said they do not believe the governor is guilty of “stolen valor,” but that he did misrepresent his record at times.",
    "author": "Bob Smith",
    "imgAuthor": "natan.jpg",
    "date_create": "2021-08-20T10:15:00+00:00",
    "theme": "Política e Integridade",
  },
  {
    "title": "Trump Isn’t Finished",
    "url": "https://www.nytimes.com/2024/08/21/opinion/trump-second-term-2025.html",
    "image": "https://static01.nyt.com/images/2024/08/21/multimedia/21edsall-cjvt/21edsall-cjvt-articleLarge.jpg",
    "description": "The damage inflicted on the nation during the former president’s first term in office pales in comparison to what he will do if he is elected to a second term.",
    "author": "Carol Davis",
    "imgAuthor": "natan.jpg",
    "date_create": "2024-04-21T11:00:00+00:00",
    "theme": "Política e Futuro",
  },
  {
    "title": "‘Dancing With the Other Arts’: The Ballets Russes’ Creative Churn",
    "url": "https://www.nytimes.com/2024/08/21/arts/dance/crafting-the-ballets-russes-morgan-library.html",
    "image": "https://static01.nyt.com/images/2024/08/20/multimedia/20morgan-russes-jglc/20morgan-russes-jglc-articleLarge.jpg",
    "description": "An exhibition at the Morgan, drawn from its collection of musical manuscripts, sheds light on one of the most collaborative periods in dance.",
    "author": "Alice Johnson",
    "imgAuthor": "natan.jpg",
    "date_create": "2024-08-21T12:20:00+00:00",
    "theme": "Arte e Colaboração",
  },
  {
    "title": "They Spouted Hate Online. Then They Were Arrested.",
    "url": "https://www.nytimes.com/2024/08/21/world/europe/uk-riots-speech.html",
    "image": null,
    "description": "As hundreds of people appear in court for their role in recent anti-immigrant riots in Britain, several are accused of fueling disorder through online posts, raising questions about the limits of free speech.",
    "author": "Bob Smith",
    "imgAuthor": "natan.jpg",
    "date_create": "2024-08-21T13:05:00+00:00",
    "theme": "Liberdade de Expressão e Justiça",
  },
  {
    "title": "What I Want a University President to Say About Campus Protests",
    "url": "https://www.nytimes.com/2024/08/20/opinion/college-protests-gaza-israel.html",
    "image": "https://static01.nyt.com/images/2024/08/21/multimedia/20stephens-ltgf/20stephens-ltgf-articleLarge.jpg",
    "description": "A community of learners is guided by the spirit of inquiry.",
    "author": "Carol Davis",
    "imgAuthor": "natan.jpg",
    "date_create": "2024-08-20T14:30:00+00:00",
    "theme": "Educação e Protestos",
  },
  {
    "title": "U.S. Push for Gaza Cease-Fire Falls Short on Key Points, Officials Say",
    "url": "https://www.nytimes.com/2024/08/20/world/middleeast/israel-hamas-us-ceasefire-gaza.html",
    "image": "https://static01.nyt.com/images/2024/08/20/multimedia/20mideast-1-zwqp/20mideast-1-zwqp-articleLarge.jpg",
    "description": "Israeli and Hamas officials have downplayed the idea that a deal could be imminent, saying that mediators’ efforts have not resolved major disputes.",
    "author": "Alice Johnson",
    "imgAuthor": "natan.jpg",
    "date_create": "2024-08-20T15:45:00+00:00",
    "theme": "Diplomacia e Conflito",
  },
  {
    "title": "Read the Final Report on the Lewiston, Maine, Mass Shootings",
    "url": "https://www.nytimes.com/interactive/2024/08/20/us/read-lewiston-maine-shooting-report.html",
    "image": "https://static01.nyt.com/images/2024/08/20/doc-759e1939-4c7d-4cf3-a493-a-promo/doc-759e1939-4c7d-4cf3-a493-a-promo-articleLarge.png",
    "description": "An independent commission investigating the October 2023 shooting emphasized failures by both the local police and the Army Reserve.",
    "author": "Bob Smith",
    "imgAuthor": "natan.jpg",
    "date_create": "2024-08-20T16:10:00+00:00",
    "theme": "Segurança e Resposta a Crises",
  },
  {
    "title": "By Day, Sun Studio Draws Tourists. At Night, Musicians Lay Down Tracks.",
    "url": "https://www.nytimes.com/2024/08/20/arts/music/sun-studio.html",
    "image": "https://static01.nyt.com/images/2024/08/21/multimedia/20sun-studio-jwqz/20sun-studio-jwqz-articleLarge.jpg",
    "description": "The historic room in Memphis has a thriving after-hours life, and generations of players come to capture a bit of the magic where rock ’n’ roll took shape.",
    "author": "Carol Davis",
    "imgAuthor": "natan.jpg",
    "date_create": "2024-08-20T17:25:00+00:00",
    "theme": "Música e Cultura",
  },
  {
    "title": "Zelensky Says Push Into Russia Shows the West’s Red Lines Are “Naïve”",
    "url": "https://www.nytimes.com/2024/08/20/world/europe/ukraine-russia-war-incursion-zelensky.html",
    "image": "https://static01.nyt.com/images/2024/08/20/multimedia/20ukraine-attack-01-zgjm/20ukraine-attack-01-zgjm-articleLarge.jpg",
    "description": "President Volodymyr Zelensky of Ukraine seized on the incursion’s success to press allies to lift a longtime restriction: the use of Western-supplied long-range weapons against Russia.",
    "author": "Alice Johnson",
    "imgAuthor": "natan.jpg",
    "date_create": "2024-08-20T18:40:00+00:00",
    "theme": "Geopolítica e Estratégia",
  }
]
